spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
          #匹配顺序
          order: 0
        - id: product-route
          uri: lb://service-product
          predicates:
            - name: Path
              args:
                patterns: /api/product/**
                matchTrailingSlash: true

